apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: user-service-deployment
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector: # service 에 대한 selector 정보를 매칭시켜줌
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service # service will look for this label
    spec: # specification for pods
      containers:
        - name: user-service
          image: seyeop03/user-service:msa.k8.01
          ports:
            - containerPort: 40003 #default one
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-datasource-url
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: user-service-port
            - name: SPRING_DATASOURCE_NAME
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-datasource-username
            - name: FIRST_SERVICE_URL
              value: first-service:40001
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer
  ports:
    - port: 40003
      targetPort: 40003
  selector:
    app: user-service